apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - traefik.io
  resources:
  - ingressroutes
  verbs:
  - get
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
