apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: traefik
  namespace: kube-system
spec:
  allocateLoadBalancerNodePorts: true
  - 10.43.86.188
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    nodePort: 30166
    port: 80
    protocol: TCP
    targetPort: 80
  - name: websecure
    nodePort: 30855
    port: 443
    protocol: TCP
    targetPort: 443
  - name: ssh
    nodePort: 31934
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: traefik
  sessionAffinity: None
  type: LoadBalancer
