apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/tags: "tag:k3s-operator"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: grafana
  type: ClusterIP
