apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-devops
  name: hello-devops
  namespace: monitoring
spec:
  - 10.43.15.171
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: hello-devops
  sessionAffinity: None
  type: ClusterIP
