apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"uptime-kuma"},"name":"uptime-kuma","namespace":"monitoring"},"spec":{"clusterIP":"10.43.52.148","clusterIPs":["10.43.52.148"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"http","port":3001,"protocol":"TCP","targetPort":3001}],"selector":{"app":"uptime-kuma"},"sessionAffinity":"None","type":"ClusterIP"}}
  labels:
    app: uptime-kuma
  name: uptime-kuma
  namespace: monitoring
spec:
  - 10.43.52.148
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: uptime-kuma
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
