apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"forgejo","namespace":"forgejo"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"forgejo"}},"template":{"metadata":{"labels":{"app":"forgejo"}},"spec":{"containers":[{"env":[{"name":"USER_UID","value":"1000"},{"name":"USER_GID","value":"1000"}],"envFrom":[{"secretRef":{"name":"forgejo-secrets"}}],"image":"data.forgejo.org/forgejo/forgejo:15","name":"forgejo","ports":[{"containerPort":3000,"name":"http"},{"containerPort":22,"name":"ssh"}],"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"250m","memory":"256Mi"}},"volumeMounts":[{"mountPath":"/data","name":"data"},{"mountPath":"/etc/localtime","name":"localtime","readOnly":true}]}],"volumes":[{"name":"data","persistentVolumeClaim":{"claimName":"forgejo-data"}},{"hostPath":{"path":"/etc/localtime","type":"File"},"name":"localtime"}]}}}}
  name: forgejo
  namespace: forgejo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: forgejo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-07-02T11:59:28+07:00"
      labels:
        app: forgejo
    spec:
      containers:
      - env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        envFrom:
        - secretRef:
            name: forgejo-secrets
        image: data.forgejo.org/forgejo/forgejo:15
        imagePullPolicy: IfNotPresent
        name: forgejo
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        - containerPort: 22
          name: ssh
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: forgejo-data
      - hostPath:
          path: /etc/localtime
          type: File
        name: localtime
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-07-02T04:54:13Z"
    lastUpdateTime: "2026-07-02T04:54:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-06-28T13:25:57Z"
    lastUpdateTime: "2026-07-02T04:59:30Z"
    message: ReplicaSet "forgejo-6b5bdb7b5b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 11
  readyReplicas: 1
  replicas: 1
  terminatingReplicas: 0
  updatedReplicas: 1
