apiVersion: v1
data:
  FORGEJO__database__DB_TYPE: c3FsaXRlMw==
  FORGEJO__server__DISABLE_SSH: ZmFsc2U=
  FORGEJO__server__DOMAIN: Z2l0Lmx1cW1hbnVsaC5teS5pZA==
  FORGEJO__server__HTTP_PORT: MzAwMA==
  FORGEJO__server__ROOT_URL: aHR0cHM6Ly9naXQubHVxbWFudWxoLm15Lmlk
  FORGEJO__server__SSH_DOMAIN: Z2l0Lmx1cW1hbnVsaC5teS5pZA==
  FORGEJO__server__SSH_LISTEN_PORT: MjI=
  FORGEJO__server__SSH_PORT: MjI=
  FORGEJO__server__START_SSH_SERVER: ZmFsc2U=
  FORGEJO__service__DISABLE_REGISTRATION: ZmFsc2U=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"forgejo-secrets","namespace":"forgejo"},"stringData":{"FORGEJO__database__DB_TYPE":"sqlite3","FORGEJO__server__DISABLE_SSH":"false","FORGEJO__server__DOMAIN":"git.example.com","FORGEJO__server__HTTP_PORT":"3000","FORGEJO__server__ROOT_URL":"https://git.example.com","FORGEJO__server__SSH_DOMAIN":"git.example.com","FORGEJO__server__SSH_LISTEN_PORT":"22","FORGEJO__server__SSH_PORT":"22","FORGEJO__server__START_SSH_SERVER":"false","FORGEJO__service__DISABLE_REGISTRATION":"false"},"type":"Opaque"}
  name: forgejo-secrets
  namespace: forgejo
type: Opaque
