apiVersion: v1
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: $(kubectl config view --raw -o jsonpath={.clusters[0].cluster.certificate-authority-data})
        server: https://10.11.7.131:6443
      name: default
    contexts:
    - context:
        cluster: default
        user: default
      name: default
    current-context: default
    kind: Config
    preferences: {}
    users:
    - name: default
      user:
        client-certificate-data: $(kubectl config view --raw -o jsonpath={.users[0].user.client-certificate-data})
        client-key-data: $(kubectl config view --raw -o jsonpath={.users[0].user.client-key-data})
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config":"apiVersion: v1\nclusters:\n- cluster:\n    certificate-authority-data: $(kubectl config view --raw -o jsonpath={.clusters[0].cluster.certificate-authority-data})\n    server: https://10.11.7.131:6443\n  name: default\ncontexts:\n- context:\n    cluster: default\n    user: default\n  name: default\ncurrent-context: default\nkind: Config\npreferences: {}\nusers:\n- name: default\n  user:\n    client-certificate-data: $(kubectl config view --raw -o jsonpath={.users[0].user.client-certificate-data})\n    client-key-data: $(kubectl config view --raw -o jsonpath={.users[0].user.client-key-data})\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"kubeconfig","namespace":"runner"}}
  name: kubeconfig
  namespace: runner
