apiVersion: v1
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RJNU9UVXpOamN3SGhjTk1qWXdOekF5TVRFeU9USTNXaGNOTXpZd05qSTVNVEV5T1RJMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RJNU9UVXpOamN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTUlFYcU9qejFnaUUwcVdvWlg3dnFDU0FMdktRcU5iaUJ3YS9TUUtKdXEKR2xOdUFJcW5yNG05bW41dWhvcWg0RytwK0MzWENudjdrUURYU3d5K3VyM3lvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXkxMVM5MUZRM0dkdnN6SS9UUVBvCk9wWkNPSW93Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUlTVDE4OVdNQm5BZ2Y0M2wwQ25IWGZrOCtDVFB1Rm0KZ2tQZEFtK2RCeWNwQWlBVUpiQ25KSVJrbFExdUh6cUxZQlk5TTNPdzVKU0dBajZmRldKKzZNUVR3QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://10.11.7.131:6443
      name: default
    contexts:
    - context:
        cluster: default
        user: default
      name: default
    current-context: default
    kind: Config
    users:
    - name: default
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJV2taNGM0Vm5pTHd3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemd5T1RrMU16WTNNQjRYRFRJMk1EY3dNakV4TWpreU4xb1hEVEkzTURjdwpNakV4TWpreU4xb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJHekxUSExMNTQycGc0cjIKV2Q0Wk55RUNHTDlJTURTZk9WUGFaaWhGYWpvY2x4Mmp5YzhONDQzcnZFZ1RnYkJkYTJPVE5FMmwxcXBlL2g4YwptaEkva2tDalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUXF5R25tbnU2bU5rcHhtMlUzRVVOK2xZV05JVEFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlCbHhBZnNac1BibjdtNTJRUlg1Wk1kV2lYcGdsQXVBd05Ed1JCcXRnYW50UUloQU9IUFp1bW9PWUVkblNrcQpSTmhNRWVtWUYvMVRBaFFueHRZMVA5YklQMkJ5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzT0RJNU9UVXpOamN3SGhjTk1qWXdOekF5TVRFeU9USTNXaGNOTXpZd05qSTVNVEV5T1RJMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzT0RJNU9UVXpOamN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSRW54QnFkSmJMNklndjRqdW5MSzVyVWp4Q3FwRTkrT2pIU3dEY2tVdlcKbUJLci83ZWE5N1NNTnNYbUNGbkhhSDA4cjJkQ1pPZFdBRlhENlFqdlUyK1hvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUtzaHA1cDd1cGpaS2NadGxOeEZECmZwV0ZqU0V3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQVBBMkRVK1lzZkUwNno4bWpoVG1WVnRlakNnaTkvNHYKT3B0a1plREgxWTdpQWlCYldBZU1CUEdLbGV4RnB6RUJSRVJFcXBjeVpiYUlDcXQxWkNicStxaW4xUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU5EOHZlaFI1ODAxbXhob2UxdFI3ekZQQjBaZDBtL1pja1pWbGRITnNmb2lvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFYk10TWNzdm5qYW1EaXZaWjNoazNJUUlZdjBnd05KODVVOXBtS0VWcU9oeVhIYVBKenczagpqZXU4U0JPQnNGMXJZNU0wVGFYV3FsNytIeHlhRWorU1FBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: ConfigMap
metadata:
  name: kubeconfig
  namespace: runner
